Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Max: 1000

Style/AsciiComments:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
  
Style/WordArray:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: [
    'describe', 'context'
  ]

Style/FrozenStringLiteralComment:
  Enabled: false