Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Max: 1000

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: [
    'describe', 'context'
  ]

Style/FrozenStringLiteralComment:
  Enabled: false